# Script for web scrapping cwc real time data
### import libraries

In [1]:
import requests
import json
from bs4 import BeautifulSoup
import pandas as pd
import datetime
from datetime import date
from datetime import timedelta
import matplotlib.pyplot as plt
import openpyxl
from openpyxl.utils.dataframe import dataframe_to_rows
import os

### 2024 June 29 updated data extracting and saving using new code

In [ ]:
# https://ffs.india-water.gov.in/web-api/getHGStationDataForFFS/

# payload : {stationCode: "'015-ERDBWN'", startDate: "2024-02-27", endDate: "2024-03-01"}
# {"stationCode":"'015-ERDBWN'","startDate":"2024-02-27","endDate":"2024-03-01"}

# Request Method:
# POST
# Status Code:
# 200 OK

In [ ]:
# data[300]['actualTime']
# data[300]['stationCode']
# data[300]['value']
# datetime.datetime.strptime(data[300]['actualTime'],datetime_format)
# data[0]

In [10]:
# df_code['name'][375:400]

In [11]:
df_code=pd.read_excel('F:\\phd_work\\cwc_real_time_data\\updated_real_time\\data_files\\2020_updated\\name-code.xlsx',index_col=0)
url = "https://ffs.india-water.gov.in/web-api/getHGStationDataForFFS/"
file_path_exp="F:\\phd_work\\cwc_real_time_data\\updated_real_time\\data_files\\2020_2024_June_25\\"
file_path_new="F:\\phd_work\\cwc_real_time_data\\updated_real_time\\data_files\\2020_2024_July_15\\"

old_file_suffix='2020_2024_6_25.xlsx'
new_file_suffix='2022_2024_7_15.xlsx'

datetime_format = '%Y-%m-%d %H:%M:%S.%f'


for name_station in df_code['name'][:100]:
    print('Data retrieving for ->',name_station)

    zz=df_code[df_code['name']==name_station].index.values
    index_name = zz[0] if len(zz) > 0 else None

    payload = {
        "stationCode": f"'{index_name}'",
        "startDate": "2024-06-26",
        "endDate": "2024-07-15"
    }
    response = requests.post(url, json=payload)

    if response.status_code == 200:
        try:
            data = response.json()
            print('Data retrived for ->',name_station)
            
            fl=[]
            df = pd.DataFrame()
            for j in data[:]:
                try:
                    ml=[j['stationCode'],datetime.datetime.strptime(j['actualTime'],datetime_format),name_station,j['value']]
                    fl.append(ml)
                except:
                    pass
            if fl:
                fl=sorted(fl)
                df=pd.DataFrame(fl)
                df.columns=['code','time','name','WSE']
                old_file=pd.read_excel(file_path_exp+name_station+old_file_suffix) # update old file end
                df_z = pd.concat([old_file, df], ignore_index=True)
                df_z = df_z.drop(columns=['Unnamed: 0'])
                df_z.to_excel(file_path_new+name_station+new_file_suffix) # new file end
                print('Data exported for station ',name_station)
            else:
                print('Data export failed for XXXXXXXXXXXXXXXXX',name_station)
                df_z=old_file
                df_z.to_excel(file_path_new+name_station+new_file_suffix)
           
        except:
            print('Data not found for the station ',name_station)
    else:
        print("Error: Failed to retrieve data. Status code:", response.status_code)

Data retrieving for -> Parwan pick-up Weir
Data not found for the station  Parwan pick-up Weir
Data retrieving for -> Kalisindh Dam
Data retrived for -> Kalisindh Dam
Data exported for station  Kalisindh Dam
Data retrieving for -> Mirawadi
Data not found for the station  Mirawadi
Data retrieving for -> Yadgir
Data retrived for -> Yadgir
Data exported for station  Yadgir
Data retrieving for -> Wadakbal
Data retrived for -> Wadakbal
Data exported for station  Wadakbal
Data retrieving for -> Ithai_WLR
Data not found for the station  Ithai_WLR
Data retrieving for -> Panchana Dam
Data retrived for -> Panchana Dam
Data exported for station  Panchana Dam
Data retrieving for -> Targaon
Data retrived for -> Targaon
Data exported for station  Targaon
Data retrieving for -> Kursela
Data retrived for -> Kursela
Data exported for station  Kursela
Data retrieving for -> VAPI
Data retrived for -> VAPI
Data exported for station  VAPI
Data retrieving for -> Yingkiong
Data retrived for -> Yingkiong
Data exported for station  Yingkiong
Data retrieving for -> RAMESHWAR
Data retrived for -> RAMESHWAR
Data exported for station  RAMESHWAR
Data retrieving for -> Jauljibi
Data not found for the station  Jauljibi
Data retrieving for -> Bamni (Ballarsha)
Data retrived for -> Bamni (Ballarsha)
Data exported for station  Bamni (Ballarsha)
Data retrieving for -> Singur Reservoir
Data retrived for -> Singur Reservoir
Data exported for station  Singur Reservoir
Data retrieving for -> Abu Road
Data retrived for -> Abu Road
Data exported for station  Abu Road
Data retrieving for -> PURNAGIRI
Data retrived for -> PURNAGIRI
Data exported for station  PURNAGIRI
Data retrieving for -> Ayodhya
Data retrived for -> Ayodhya
Data exported for station  Ayodhya
Data retrieving for -> Madkote
Data not found for the station  Madkote
Data retrieving for -> Irilbung_WLR
Data not found for the station  Irilbung_WLR
Data retrieving for -> Bhagalpur
Data retrived for -> Bhagalpur
Data exported for station  Bhagalpur
Data retrieving for -> RUPALIGAD
Data retrived for -> RUPALIGAD
Data exported for station  RUPALIGAD
Data retrieving for -> Gudha Dam
Data retrived for -> Gudha Dam
Data exported for station  Gudha Dam
Data retrieving for -> Moradabad
Data retrived for -> Moradabad
Data exported for station  Moradabad
Data retrieving for -> Dabri
Data retrived for -> Dabri
Data exported for station  Dabri
Data retrieving for -> Manderial
Data retrived for -> Manderial
Data exported for station  Manderial
Data retrieving for -> Getalsud Reservoir
Data retrived for -> Getalsud Reservoir
Data exported for station  Getalsud Reservoir
Data retrieving for -> SARANGKHEDA
Data retrived for -> SARANGKHEDA
Data exported for station  SARANGKHEDA
Data retrieving for -> Malkhed
Data not found for the station  Malkhed
Data retrieving for -> Tilaiya Reservoir
Data retrived for -> Tilaiya Reservoir
Data exported for station  Tilaiya Reservoir
Data retrieving for -> Dharoi Dam
Data retrived for -> Dharoi Dam
Data exported for station  Dharoi Dam
Data retrieving for -> NT Road Crossing Jia-Bharali
Data retrived for -> NT Road Crossing Jia-Bharali
Data exported for station  NT Road Crossing Jia-Bharali
Data retrieving for -> BAMRUL
Data not found for the station  BAMRUL
Data retrieving for -> Gaura
Data retrived for -> Gaura
Data exported for station  Gaura
Data retrieving for -> KATRAGADDA
Data retrived for -> KATRAGADDA
Data export failed for XXXXXXXXXXXXXXXXX KATRAGADDA
Data retrieving for -> Harshil
Data not found for the station  Harshil
Data retrieving for -> NATHPA
Data retrived for -> NATHPA
Data exported for station  NATHPA
Data retrieving for -> PANCHARATNA
Data retrived for -> PANCHARATNA
Data exported for station  PANCHARATNA
Data retrieving for -> Ghodopipli
Data retrived for -> Ghodopipli
Data exported for station  Ghodopipli
Data retrieving for -> ETAWAH
Data retrived for -> ETAWAH
Data exported for station  ETAWAH
Data retrieving for -> Mohammad Ganj
Data retrived for -> Mohammad Ganj
Data exported for station  Mohammad Ganj
Data retrieving for -> Sonapur
Data retrived for -> Sonapur
Data exported for station  Sonapur
Data retrieving for -> Hipparagi Barrage
Data retrived for -> Hipparagi Barrage
Data exported for station  Hipparagi Barrage
Data retrieving for -> Kakrahi
Data retrived for -> Kakrahi
Data exported for station  Kakrahi
Data retrieving for -> Hathnikund Barrage
Data retrived for -> Hathnikund Barrage
Data exported for station  Hathnikund Barrage
Data retrieving for -> PIMPRI
Data retrived for -> PIMPRI
Data exported for station  PIMPRI
Data retrieving for -> PVNRao Kantanapally Project
Data retrived for -> PVNRao Kantanapally Project
Data exported for station  PVNRao Kantanapally Project
Data retrieving for -> Chepan
Data retrived for -> Chepan
Data exported for station  Chepan
Data retrieving for -> Jamshedpur
Data retrived for -> Jamshedpur
Data exported for station  Jamshedpur
Data retrieving for -> Paonta
Data retrived for -> Paonta
Data exported for station  Paonta
Data retrieving for -> NAWTHA
Data retrived for -> NAWTHA
Data exported for station  NAWTHA
Data retrieving for -> Kasmara
Data retrived for -> Kasmara
Data exported for station  Kasmara
Data retrieving for -> Mount Abu
Data retrived for -> Mount Abu
Data export failed for XXXXXXXXXXXXXXXXX Mount Abu
Data retrieving for -> Neamatighat
Data retrived for -> Neamatighat
Data exported for station  Neamatighat
Data retrieving for -> Sapawada
Data retrived for -> Sapawada
Data exported for station  Sapawada
Data retrieving for -> Ganeshpura
Data retrived for -> Ganeshpura
Data exported for station  Ganeshpura
Data retrieving for -> Isapur Reservoir
Data retrived for -> Isapur Reservoir
Data exported for station  Isapur Reservoir
Data retrieving for -> Garhmukteshwar
Data retrived for -> Garhmukteshwar
Data exported for station  Garhmukteshwar
Data retrieving for -> Matijuri
Data retrived for -> Matijuri
Data export failed for XXXXXXXXXXXXXXXXX Matijuri
Data retrieving for -> DHUPESHWAR
Data retrived for -> DHUPESHWAR
Data exported for station  DHUPESHWAR
Data retrieving for -> Panposh
Data retrived for -> Panposh
Data exported for station  Panposh
Data retrieving for -> TALASWADA
Data retrived for -> TALASWADA
Data exported for station  TALASWADA
Data retrieving for -> WANKHED
Data retrived for -> WANKHED
Data exported for station  WANKHED
Data retrieving for -> Amarpur
Data retrived for -> Amarpur
Data exported for station  Amarpur
Data retrieving for -> Mandleshwar
Data retrived for -> Mandleshwar
Data exported for station  Mandleshwar
Data retrieving for -> Vautha
Data retrived for -> Vautha
Data exported for station  Vautha
Data retrieving for -> Handia
Data retrived for -> Handia
Data exported for station  Handia
Data retrieving for -> Mahulpali
Data retrived for -> Mahulpali
Data exported for station  Mahulpali
Data retrieving for -> MOORANG
Data retrived for -> MOORANG
Data exported for station  MOORANG
Data retrieving for -> Muri
Data retrived for -> Muri
Data exported for station  Muri
Data retrieving for -> Seohara
Data retrived for -> Seohara
Data exported for station  Seohara
Data retrieving for -> Bamni
Data retrived for -> Bamni
Data exported for station  Bamni
Data retrieving for -> ID Lohaghat
Data not found for the station  ID Lohaghat
Data retrieving for -> Jalaput dam (Machkund)
Data retrived for -> Jalaput dam (Machkund)
Data exported for station  Jalaput dam (Machkund)
Data retrieving for -> Tenughat Reservoir
Data retrived for -> Tenughat Reservoir
Data exported for station  Tenughat Reservoir
Data retrieving for -> Kesinga
Data retrived for -> Kesinga
Data exported for station  Kesinga
Data retrieving for -> Bisalpur Reservoir
Data retrived for -> Bisalpur Reservoir
Data exported for station  Bisalpur Reservoir
Data retrieving for -> Bhandara
Data retrived for -> Bhandara
Data exported for station  Bhandara
Data retrieving for -> MALLI MADUGU.
Data not found for the station  MALLI MADUGU.
Data retrieving for -> AGRA (J.B.)
Data retrived for -> AGRA (J.B.)
Data exported for station  AGRA (J.B.)
Data retrieving for -> MUSIRI
Data retrived for -> MUSIRI
Data exported for station  MUSIRI
Data retrieving for -> RIHAND DAM
Data retrived for -> RIHAND DAM
Data exported for station  RIHAND DAM
Data retrieving for -> Mathani Road Bridge
Data retrived for -> Mathani Road Bridge
Data exported for station  Mathani Road Bridge
Data retrieving for -> Dhengraghat
Data retrived for -> Dhengraghat
Data exported for station  Dhengraghat
Data retrieving for -> Phulgaon
Data retrived for -> Phulgaon
Data exported for station  Phulgaon
Data retrieving for -> Turtipar
Data retrived for -> Turtipar
Data exported for station  Turtipar
Data retrieving for -> Prakasam Barrage
Data retrived for -> Prakasam Barrage
Data exported for station  Prakasam Barrage
Data retrieving for -> Passighat
Data retrived for -> Passighat
Data exported for station  Passighat
Data retrieving for -> Banbasa Barrage
Data retrived for -> Banbasa Barrage
Data exported for station  Banbasa Barrage
Data retrieving for -> Chupkoli
Data retrived for -> Chupkoli
Data exported for station  Chupkoli
Data retrieving for -> Mirzapur
Data retrived for -> Mirzapur
Data exported for station  Mirzapur
Data retrieving for -> Tungabhadra Dam
Data retrived for -> Tungabhadra Dam
Data exported for station  Tungabhadra Dam
Data retrieving for -> Kantamal
Data retrived for -> Kantamal
Data exported for station  Kantamal
Data retrieving for -> Narayanapura Reservoir
Data retrived for -> Narayanapura Reservoir
Data exported for station  Narayanapura Reservoir
Data retrieving for -> Jhanjharpur
Data retrived for -> Jhanjharpur
Data exported for station  Jhanjharpur
Data retrieving for -> Mawi
Data retrived for -> Mawi
Data exported for station  Mawi
Data retrieving for -> SUNDAR DAM
Data retrived for -> SUNDAR DAM
Data export failed for XXXXXXXXXXXXXXXXX SUNDAR DAM
Data retrieving for -> Kashinagar
Data retrived for -> Kashinagar
Data exported for station  Kashinagar
Data retrieving for -> RAJGHAT DAM
Data retrived for -> RAJGHAT DAM
Data exported for station  RAJGHAT DAM
Data retrieving for -> Nanded
Data retrived for -> Nanded
Data exported for station  Nanded

In [3]:
name_station

'Kokrajhar'

In [5]:
df_x=pd.read_excel("F://phd_work//cwc_real_time_data//updated_real_time//data_files/2020_2024_feb/Tikarpara2020_2024feb.xlsx")
df_y=pd.read_excel("F://phd_work//cwc_real_time_data//updated_real_time/data_files/2020_2024_april_new/Tikarpara2024_mar_to_27_april.xlsx")

In [13]:
df_x

       Unnamed: 0         code                time       name    WSE
0               0  034-MDBURLA 2020-01-01 08:00:00  Tikarpara  54.18
1               1  034-MDBURLA 2020-01-01 13:00:00  Tikarpara  54.18
2               2  034-MDBURLA 2020-01-01 18:00:00  Tikarpara  54.20
3               3  034-MDBURLA 2020-01-02 08:00:00  Tikarpara  54.30
4               4  034-MDBURLA 2020-01-02 13:00:00  Tikarpara  54.30
...           ...          ...                 ...        ...    ...
17389       17389  034-MDBURLA 2024-02-28 13:00:00  Tikarpara  54.35
17390       17390  034-MDBURLA 2024-02-28 18:00:00  Tikarpara  54.35
17391       17391  034-MDBURLA 2024-02-29 08:00:00  Tikarpara  54.37
17392       17392  034-MDBURLA 2024-02-29 13:00:00  Tikarpara  54.37
17393       17393  034-MDBURLA 2024-02-29 18:00:00  Tikarpara  54.38

[17394 rows x 5 columns]

In [15]:
# df_z=df_x.append(df_y)
# df_x.reset_index(drop=True, inplace=True)

# # Reset index for df_y
# df_y.reset_index(drop=True, inplace=True)

# # Append df_y to df_x
# df_z = df_x.append(df_y, ignore_index=True)
# df_z = pd.concat([df_x, df_y], ignore_index=True)
df_z = df_z.drop(columns=['Unnamed: 0'])

df_z

              code                time       name    WSE
0      034-MDBURLA 2020-01-01 08:00:00  Tikarpara  54.18
1      034-MDBURLA 2020-01-01 13:00:00  Tikarpara  54.18
2      034-MDBURLA 2020-01-01 18:00:00  Tikarpara  54.20
3      034-MDBURLA 2020-01-02 08:00:00  Tikarpara  54.30
4      034-MDBURLA 2020-01-02 13:00:00  Tikarpara  54.30
...            ...                 ...        ...    ...
17563  034-MDBURLA 2024-04-26 13:00:00  Tikarpara  54.17
17564  034-MDBURLA 2024-04-26 18:00:00  Tikarpara  54.17
17565  034-MDBURLA 2024-04-27 08:00:00  Tikarpara  54.17
17566  034-MDBURLA 2024-04-27 13:00:00  Tikarpara  54.17
17567  034-MDBURLA 2024-04-27 18:00:00  Tikarpara  54.19

[17568 rows x 4 columns]

### date range and html json responses

In [2]:
sdate1="2024-08-01"
edate1="2024-09-20"
# sdate1="2023-08-22"    #yyyy-mm-dd
# edate1="2023-08-22"    #yyyy-mm-dd # may(5) 31  sep(9) 30


url1=f"""https://ffs.india-water.gov.in/iam/api/new-entry-data/specification/sorted?sort-criteria=%7B%22sortOrderDtos%22:%5B%7B%22sortDirection%22:%22ASC%22,%22field%22:%22id.dataTime%22%7D%5D%7D&specification=%7B%22where%22:%7B%22where%22:%7B%22expression%22:%7B%22valueIsRelationField%22:false,%22fieldName%22:%22id.datatypeCode%22,%22operator%22:%22eq%22,%22value%22:%22HHS%22%7D%7D,%22and%22:%7B%22expression%22:%7B%22valueIsRelationField%22:false,%22fieldName%22:%22dataValue%22,%22operator%22:%22null%22,%22value%22:%22false%22%7D%7D%7D,%22and%22:%7B%22expression%22:%7B%22valueIsRelationField%22:false,%22fieldName%22:%22id.dataTime%22,%22operator%22:%22btn%22,%22value%22:%22{sdate1}T00:00:00.250,{edate1}T23:59:59.250%22%7D%7D%7D"""

md1=None

session1=requests.session()

try:
    data1 = session1.get(url1, timeout=10000)
    soup1 = BeautifulSoup(data1.content, 'html.parser')
    md1 = json.loads(soup1.get_text())
except requests.exceptions.ConnectionError as e:
    print(f"ConnectionError: {e}")
except Exception as e:
    print(f"An error occurred: {e}")

ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

In [ ]:
sdate1="2011-01-01"
edate1="2011-12-31"
# sdate1="2023-08-22"    #yyyy-mm-dd
# edate1="2023-08-22"    #yyyy-mm-dd # may(5) 31  sep(9) 30


url2=f"""https://ffs.india-water.gov.in/iam/api/new-entry-data/specification/sorted?sort-criteria=%7B%22sortOrderDtos%22:%5B%7B%22sortDirection%22:%22ASC%22,%22field%22:%22id.dataTime%22%7D%5D%7D&specification=%7B%22where%22:%7B%22where%22:%7B%22expression%22:%7B%22valueIsRelationField%22:false,%22fieldName%22:%22id.datatypeCode%22,%22operator%22:%22eq%22,%22value%22:%22HHS%22%7D%7D,%22and%22:%7B%22expression%22:%7B%22valueIsRelationField%22:false,%22fieldName%22:%22dataValue%22,%22operator%22:%22null%22,%22value%22:%22false%22%7D%7D%7D,%22and%22:%7B%22expression%22:%7B%22valueIsRelationField%22:false,%22fieldName%22:%22id.dataTime%22,%22operator%22:%22btn%22,%22value%22:%22{sdate1}T00:00:00.250,{edate1}T23:59:59.250%22%7D%7D%7D"""

md2=None

session2=requests.session()

try:
    data2 = session2.get(url2, timeout=10000)
    soup2 = BeautifulSoup(data2.content, 'html.parser')
    md2 = json.loads(soup2.get_text())
except requests.exceptions.ConnectionError as e:
    print(f"ConnectionError: {e}")
except Exception as e:
    print(f"An error occurred: {e}")

In [ ]:
sdate1="2012-01-01"
edate1="2012-12-31"
# sdate1="2023-08-22"    #yyyy-mm-dd
# edate1="2023-08-22"    #yyyy-mm-dd # may(5) 31  sep(9) 30


url3=f"""https://ffs.india-water.gov.in/iam/api/new-entry-data/specification/sorted?sort-criteria=%7B%22sortOrderDtos%22:%5B%7B%22sortDirection%22:%22ASC%22,%22field%22:%22id.dataTime%22%7D%5D%7D&specification=%7B%22where%22:%7B%22where%22:%7B%22expression%22:%7B%22valueIsRelationField%22:false,%22fieldName%22:%22id.datatypeCode%22,%22operator%22:%22eq%22,%22value%22:%22HHS%22%7D%7D,%22and%22:%7B%22expression%22:%7B%22valueIsRelationField%22:false,%22fieldName%22:%22dataValue%22,%22operator%22:%22null%22,%22value%22:%22false%22%7D%7D%7D,%22and%22:%7B%22expression%22:%7B%22valueIsRelationField%22:false,%22fieldName%22:%22id.dataTime%22,%22operator%22:%22btn%22,%22value%22:%22{sdate1}T00:00:00.250,{edate1}T23:59:59.250%22%7D%7D%7D"""

md3=None

session3=requests.session()

try:
    data3 = session3.get(url3, timeout=10000)
    soup3 = BeautifulSoup(data3.content, 'html.parser')
    md3 = json.loads(soup3.get_text())
except requests.exceptions.ConnectionError as e:
    print(f"ConnectionError: {e}")
except Exception as e:
    print(f"An error occurred: {e}")

In [ ]:
sdate1="2013-01-01"
edate1="2013-12-31"
# sdate1="2023-08-22"    #yyyy-mm-dd
# edate1="2023-08-22"    #yyyy-mm-dd # may(5) 31  sep(9) 30


url4=f"""https://ffs.india-water.gov.in/iam/api/new-entry-data/specification/sorted?sort-criteria=%7B%22sortOrderDtos%22:%5B%7B%22sortDirection%22:%22ASC%22,%22field%22:%22id.dataTime%22%7D%5D%7D&specification=%7B%22where%22:%7B%22where%22:%7B%22expression%22:%7B%22valueIsRelationField%22:false,%22fieldName%22:%22id.datatypeCode%22,%22operator%22:%22eq%22,%22value%22:%22HHS%22%7D%7D,%22and%22:%7B%22expression%22:%7B%22valueIsRelationField%22:false,%22fieldName%22:%22dataValue%22,%22operator%22:%22null%22,%22value%22:%22false%22%7D%7D%7D,%22and%22:%7B%22expression%22:%7B%22valueIsRelationField%22:false,%22fieldName%22:%22id.dataTime%22,%22operator%22:%22btn%22,%22value%22:%22{sdate1}T00:00:00.250,{edate1}T23:59:59.250%22%7D%7D%7D"""

md4=None

session4=requests.session()

try:
    data4 = session4.get(url4, timeout=10000)
    soup4 = BeautifulSoup(data4.content, 'html.parser')
    md4 = json.loads(soup4.get_text())
except requests.exceptions.ConnectionError as e:
    print(f"ConnectionError: {e}")
except Exception as e:
    print(f"An error occurred: {e}")

In [ ]:
sdate1="2014-01-01"
edate1="2014-12-31"
# sdate1="2023-08-22"    #yyyy-mm-dd
# edate1="2023-08-22"    #yyyy-mm-dd # may(5) 31  sep(9) 30


url5=f"""https://ffs.india-water.gov.in/iam/api/new-entry-data/specification/sorted?sort-criteria=%7B%22sortOrderDtos%22:%5B%7B%22sortDirection%22:%22ASC%22,%22field%22:%22id.dataTime%22%7D%5D%7D&specification=%7B%22where%22:%7B%22where%22:%7B%22expression%22:%7B%22valueIsRelationField%22:false,%22fieldName%22:%22id.datatypeCode%22,%22operator%22:%22eq%22,%22value%22:%22HHS%22%7D%7D,%22and%22:%7B%22expression%22:%7B%22valueIsRelationField%22:false,%22fieldName%22:%22dataValue%22,%22operator%22:%22null%22,%22value%22:%22false%22%7D%7D%7D,%22and%22:%7B%22expression%22:%7B%22valueIsRelationField%22:false,%22fieldName%22:%22id.dataTime%22,%22operator%22:%22btn%22,%22value%22:%22{sdate1}T00:00:00.250,{edate1}T23:59:59.250%22%7D%7D%7D"""

md5=None

session5=requests.session()

try:
    data5 = session5.get(url5, timeout=10000)
    soup5 = BeautifulSoup(data5.content, 'html.parser')
    md5 = json.loads(soup5.get_text())
except requests.exceptions.ConnectionError as e:
    print(f"ConnectionError: {e}")
except Exception as e:
    print(f"An error occurred: {e}")

In [ ]:
sdate1="2015-01-01"
edate1="2015-12-31"
# sdate1="2023-08-22"    #yyyy-mm-dd
# edate1="2023-08-22"    #yyyy-mm-dd # may(5) 31  sep(9) 30


url6=f"""https://ffs.india-water.gov.in/iam/api/new-entry-data/specification/sorted?sort-criteria=%7B%22sortOrderDtos%22:%5B%7B%22sortDirection%22:%22ASC%22,%22field%22:%22id.dataTime%22%7D%5D%7D&specification=%7B%22where%22:%7B%22where%22:%7B%22expression%22:%7B%22valueIsRelationField%22:false,%22fieldName%22:%22id.datatypeCode%22,%22operator%22:%22eq%22,%22value%22:%22HHS%22%7D%7D,%22and%22:%7B%22expression%22:%7B%22valueIsRelationField%22:false,%22fieldName%22:%22dataValue%22,%22operator%22:%22null%22,%22value%22:%22false%22%7D%7D%7D,%22and%22:%7B%22expression%22:%7B%22valueIsRelationField%22:false,%22fieldName%22:%22id.dataTime%22,%22operator%22:%22btn%22,%22value%22:%22{sdate1}T00:00:00.250,{edate1}T23:59:59.250%22%7D%7D%7D"""

md6=None

session6=requests.session()

try:
    data6 = session6.get(url6, timeout=10000)
    soup6 = BeautifulSoup(data6.content, 'html.parser')
    md6 = json.loads(soup6.get_text())
except requests.exceptions.ConnectionError as e:
    print(f"ConnectionError: {e}")
except Exception as e:
    print(f"An error occurred: {e}")

In [ ]:
sdate1="2016-01-01"
edate1="2016-12-31"
# sdate1="2023-08-22"    #yyyy-mm-dd
# edate1="2023-08-22"    #yyyy-mm-dd # may(5) 31  sep(9) 30


url7=f"""https://ffs.india-water.gov.in/iam/api/new-entry-data/specification/sorted?sort-criteria=%7B%22sortOrderDtos%22:%5B%7B%22sortDirection%22:%22ASC%22,%22field%22:%22id.dataTime%22%7D%5D%7D&specification=%7B%22where%22:%7B%22where%22:%7B%22expression%22:%7B%22valueIsRelationField%22:false,%22fieldName%22:%22id.datatypeCode%22,%22operator%22:%22eq%22,%22value%22:%22HHS%22%7D%7D,%22and%22:%7B%22expression%22:%7B%22valueIsRelationField%22:false,%22fieldName%22:%22dataValue%22,%22operator%22:%22null%22,%22value%22:%22false%22%7D%7D%7D,%22and%22:%7B%22expression%22:%7B%22valueIsRelationField%22:false,%22fieldName%22:%22id.dataTime%22,%22operator%22:%22btn%22,%22value%22:%22{sdate1}T00:00:00.250,{edate1}T23:59:59.250%22%7D%7D%7D"""

md7=None

session7=requests.session()

try:
    data7 = session7.get(url7, timeout=10000)
    soup7 = BeautifulSoup(data7.content, 'html.parser')
    md7 = json.loads(soup7.get_text())
except requests.exceptions.ConnectionError as e:
    print(f"ConnectionError: {e}")
except Exception as e:
    print(f"An error occurred: {e}")

In [ ]:
sdate1="2017-01-01"
edate1="2017-12-31"
# sdate1="2023-08-22"    #yyyy-mm-dd
# edate1="2023-08-22"    #yyyy-mm-dd # may(5) 31  sep(9) 30


url8=f"""https://ffs.india-water.gov.in/iam/api/new-entry-data/specification/sorted?sort-criteria=%7B%22sortOrderDtos%22:%5B%7B%22sortDirection%22:%22ASC%22,%22field%22:%22id.dataTime%22%7D%5D%7D&specification=%7B%22where%22:%7B%22where%22:%7B%22expression%22:%7B%22valueIsRelationField%22:false,%22fieldName%22:%22id.datatypeCode%22,%22operator%22:%22eq%22,%22value%22:%22HHS%22%7D%7D,%22and%22:%7B%22expression%22:%7B%22valueIsRelationField%22:false,%22fieldName%22:%22dataValue%22,%22operator%22:%22null%22,%22value%22:%22false%22%7D%7D%7D,%22and%22:%7B%22expression%22:%7B%22valueIsRelationField%22:false,%22fieldName%22:%22id.dataTime%22,%22operator%22:%22btn%22,%22value%22:%22{sdate1}T00:00:00.250,{edate1}T23:59:59.250%22%7D%7D%7D"""

md8=None

session8=requests.session()

try:
    data8 = session8.get(url8, timeout=10000)
    soup8 = BeautifulSoup(data8.content, 'html.parser')
    md8 = json.loads(soup8.get_text())
except requests.exceptions.ConnectionError as e:
    print(f"ConnectionError: {e}")
except Exception as e:
    print(f"An error occurred: {e}")

In [ ]:
sdate1="2018-01-01"
edate1="2018-12-31"
# sdate1="2023-08-22"    #yyyy-mm-dd
# edate1="2023-08-22"    #yyyy-mm-dd # may(5) 31  sep(9) 30


url9=f"""https://ffs.india-water.gov.in/iam/api/new-entry-data/specification/sorted?sort-criteria=%7B%22sortOrderDtos%22:%5B%7B%22sortDirection%22:%22ASC%22,%22field%22:%22id.dataTime%22%7D%5D%7D&specification=%7B%22where%22:%7B%22where%22:%7B%22expression%22:%7B%22valueIsRelationField%22:false,%22fieldName%22:%22id.datatypeCode%22,%22operator%22:%22eq%22,%22value%22:%22HHS%22%7D%7D,%22and%22:%7B%22expression%22:%7B%22valueIsRelationField%22:false,%22fieldName%22:%22dataValue%22,%22operator%22:%22null%22,%22value%22:%22false%22%7D%7D%7D,%22and%22:%7B%22expression%22:%7B%22valueIsRelationField%22:false,%22fieldName%22:%22id.dataTime%22,%22operator%22:%22btn%22,%22value%22:%22{sdate1}T00:00:00.250,{edate1}T23:59:59.250%22%7D%7D%7D"""

md9=None

session9=requests.session()

try:
    data9 = session9.get(url9, timeout=10000)
    soup9 = BeautifulSoup(data9.content, 'html.parser')
    md9 = json.loads(soup9.get_text())
except requests.exceptions.ConnectionError as e:
    print(f"ConnectionError: {e}")
except Exception as e:
    print(f"An error occurred: {e}")

In [ ]:
sdate1="2019-01-01"
edate1="2019-12-31"
# sdate1="2023-08-22"    #yyyy-mm-dd
# edate1="2023-08-22"    #yyyy-mm-dd # may(5) 31  sep(9) 30


url10=f"""https://ffs.india-water.gov.in/iam/api/new-entry-data/specification/sorted?sort-criteria=%7B%22sortOrderDtos%22:%5B%7B%22sortDirection%22:%22ASC%22,%22field%22:%22id.dataTime%22%7D%5D%7D&specification=%7B%22where%22:%7B%22where%22:%7B%22expression%22:%7B%22valueIsRelationField%22:false,%22fieldName%22:%22id.datatypeCode%22,%22operator%22:%22eq%22,%22value%22:%22HHS%22%7D%7D,%22and%22:%7B%22expression%22:%7B%22valueIsRelationField%22:false,%22fieldName%22:%22dataValue%22,%22operator%22:%22null%22,%22value%22:%22false%22%7D%7D%7D,%22and%22:%7B%22expression%22:%7B%22valueIsRelationField%22:false,%22fieldName%22:%22id.dataTime%22,%22operator%22:%22btn%22,%22value%22:%22{sdate1}T00:00:00.250,{edate1}T23:59:59.250%22%7D%7D%7D"""

md10=None

session10=requests.session()

try:
    data10 = session10.get(url10, timeout=10000)
    soup10 = BeautifulSoup(data10.content, 'html.parser')
    md10 = json.loads(soup10.get_text())
except requests.exceptions.ConnectionError as e:
    print(f"ConnectionError: {e}")
except Exception as e:
    print(f"An error occurred: {e}")

In [ ]:
# import pickle

export_filename = 'md1_export.pkl'
with open(export_filename, 'wb') as export_file:
    pickle.dump(md1, export_file)

# Later, when you need to import md1 from the local file
# import_filename = 'md1_export.pkl'
# with open(import_filename, 'rb') as import_file:
#     md1_imported = pickle.load(import_file)

In [ ]:
# md1
# station_names

In [ ]:
# md4
# md10

### updating data in database
##### here yesterdays data will be added to existing retrived data base

In [ ]:
df_code=pd.read_excel('F:\\phd_work\\cwc_real_time_data\\updated_real_time\\data_files\\2020_updated\\name-code.xlsx',index_col=0)

In [ ]:
# df_code=df_code.iloc[152:]
# df_code

In [ ]:
# df_code=pd.read_excel('name-code.xlsx',index_col=0)
file_path_exp="F:\\phd_work\\cwc_real_time_data\\updated_real_time\\data_files\\2010_2019\\"
for name_x in df_code['name']:
    print(name_x)
    df1=df_code[df_code['name']==name_x] # remove this line if want to download all data
    dic=df1.T.to_dict()
    fl=[]
    
    print('processing md1')

    for j in md1[:]:
        try:

            ml=[j['id']['stationCode'],datetime.datetime.fromisoformat(j['id']['dataTime']),dic[j['id']['stationCode']]['name'],j['dataValue']]
            fl.append(ml)
        except:
            pass
        
            
    print('processing md2')

    for j in md2[:]:
        try:

            ml=[j['id']['stationCode'],datetime.datetime.fromisoformat(j['id']['dataTime']),dic[j['id']['stationCode']]['name'],j['dataValue']]
            fl.append(ml)
        except:
            pass
    
    print('processing md3')
 
    for j in md3[:]:
        try:

            ml=[j['id']['stationCode'],datetime.datetime.fromisoformat(j['id']['dataTime']),dic[j['id']['stationCode']]['name'],j['dataValue']]
            fl.append(ml)
        except:
            pass
        
    for j in md4[:]:
        try:

#             print('processing md4')
            ml=[j['id']['stationCode'],datetime.datetime.fromisoformat(j['id']['dataTime']),dic[j['id']['stationCode']]['name'],j['dataValue']]
            fl.append(ml)
        except:
            pass
        
    for j in md5[:]:
        try:

#             print('processing md5')
            ml=[j['id']['stationCode'],datetime.datetime.fromisoformat(j['id']['dataTime']),dic[j['id']['stationCode']]['name'],j['dataValue']]
            fl.append(ml)
        except:
            pass
    
    print('processing md6')

    for j in md6[:]:
        try:

            ml=[j['id']['stationCode'],datetime.datetime.fromisoformat(j['id']['dataTime']),dic[j['id']['stationCode']]['name'],j['dataValue']]
            fl.append(ml)
        except:
            pass
        
    for j in md7[:]:
        try:

#             print('processing md7')
            ml=[j['id']['stationCode'],datetime.datetime.fromisoformat(j['id']['dataTime']),dic[j['id']['stationCode']]['name'],j['dataValue']]
            fl.append(ml)
        except:
            pass
        
    for j in md8[:]:
        try:

#             print('processing md8')
            ml=[j['id']['stationCode'],datetime.datetime.fromisoformat(j['id']['dataTime']),dic[j['id']['stationCode']]['name'],j['dataValue']]
            fl.append(ml)
        except:
            pass
        
    for j in md9[:]:
        try:

#             print('processing md9')
            ml=[j['id']['stationCode'],datetime.datetime.fromisoformat(j['id']['dataTime']),dic[j['id']['stationCode']]['name'],j['dataValue']]
            fl.append(ml)
        except:
            pass
        
    print('processing md10')

    for j in md10[:]:
        try:

            ml=[j['id']['stationCode'],datetime.datetime.fromisoformat(j['id']['dataTime']),dic[j['id']['stationCode']]['name'],j['dataValue']]
            fl.append(ml)
        except:
            pass


        
    try:   
        fl=sorted(fl)   
        df=pd.DataFrame(fl)
        df.columns=['code','time','name','WSE']
        df.to_excel(file_path_exp+name_x+'2010_2018.xlsx') # change file name here
        print("file export success for station {name_x}")
    except:
        pass

In [ ]:
# Import necessary libraries
# import datetime
# import pandas as pd

# Assuming df_code, md1, and other variables are already defined before this point

file_path_exp = "F:\\phd_work\\cwc_real_time_data\\updated_real_time\\data_files\\2010_2019\\"

for name_x in df_code['name']:
    print(name_x)
    
    # Filter df_code based on the current name_x
    df1 = df_code[df_code['name'] == name_x]
    dic = df1.T.to_dict()
    
    # Initialize an empty list to store data for the current name_x
    fl = []
    a = 0
    
    # Process each md list using list comprehension
    for md in [md1, md2, md3, md4, md5, md6, md7, md8, md9, md10]:
        a += 1
        print('processing md', a)
        fl += [
            [
                j['id']['stationCode'],
                datetime.datetime.fromisoformat(j['id']['dataTime']),
                dic.get(j['id']['stationCode'], {}).get('name', None),
                j.get('dataValue', None)
            ]
            for j in md if 'id' in j and 'dataTime' in j['id'] and 'dataValue' in j
        ]

    try:
        fl = sorted(fl)
        df = pd.DataFrame(fl)
        df.columns = ['code', 'time', 'name', 'WSE']
        df.to_excel(file_path_exp + name_x + '2010_2018.xlsx')  # Change file name here
        print(f"File export success for station {name_x}")
    except Exception as e:
        print(f"An error occurred while exporting data for station {name_x}: {e}")

In [ ]:
# df_code=pd.read_excel('name-code.xlsx',index_col=0)
# df1=df_code[df_code['name']=='Tikarpara'] # remove this line if want to download all data
# dic=df1.T.to_dict()
# fl=[]
# for j in md1[:]:
#     try:

#         ml=[j['id']['stationCode'],datetime.datetime.fromisoformat(j['id']['dataTime']),dic[j['id']['stationCode']]['name'],j['dataValue']]
#         fl.append(ml)
#     except:
#         pass
# fl
# # updated_path = "F:\\phd_work\\cwc_real_time_data\\updated_real_time\\data_files\\2020_updated\\data"
# # excel_file=updated_path+'\\'+name_x+'2020_to'+d2_under+'.xlsx'
# # excel_file_new=updated_path+'\\'+name_x+'2020_to'+d1_under+'.xlsx'
# fl=sorted(fl)   
# df=pd.DataFrame(fl)
# # df.columns=['code','time','name','WSE']
# # df=df.loc[23:]
# round(len(fl)/2)-1